#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";

const packageVersion = readPackageVersion();
const shortcutSourcePath = "src/shortcut.ts";
const shortcutOutputBase = basename(shortcutSourcePath, ".ts");

type ProjectFile = {
  path: string;
  contents: string;
};

/**
 * 执行 create-shortcutsflow 初始化入口。
 */
function main(argv: string[]): void {
  if (argv.includes("--help") || argv.includes("-h")) {
    printHelp();
    return;
  }

  const target = argv[0];

  if (!target) {
    printHelp();
    process.exitCode = 1;
    return;
  }

  createProject(target);
}

/**
 * 在目标目录写入 ShortcutsFlow 开发者项目模板。
 */
function createProject(target: string): void {
  const root = resolve(target);
  const projectName = normalizePackageName(basename(root));

  ensureWritableTarget(root);

  for (const file of createProjectFiles(projectName)) {
    const filePath = join(root, file.path);

    mkdirSync(dirname(filePath), {
      recursive: true,
    });
    writeFileSync(filePath, file.contents);
  }

  console.log(`Created ShortcutsFlow project in ${root}`);
  console.log("");
  console.log("Next steps:");
  console.log(`  cd ${target}`);
  console.log("  npm install");
  console.log("  npm run build");
  console.log("  npm run check");
  console.log("  npm run inspect");
  console.log("  npm run sign");
}

/**
 * 确保目标目录不存在或为空目录。
 */
function ensureWritableTarget(root: string): void {
  if (!existsSync(root)) {
    mkdirSync(root, {
      recursive: true,
    });
    return;
  }

  if (readdirSync(root).length > 0) {
    throw new Error(`Target directory is not empty: ${root}`);
  }
}

/**
 * 创建项目模板文件列表。
 */
function createProjectFiles(projectName: string): ProjectFile[] {
  return [
    {
      path: "package.json",
      contents: `${JSON.stringify(createPackageJson(projectName), null, 2)}\n`,
    },
    {
      path: "shortcuts.config.ts",
      contents: `export default {
  shortcuts: [
    "src/shortcut.ts",
  ],
  outputDir: "dist",
};
`,
    },
    {
      path: shortcutSourcePath,
      contents: `import { defineShortcut, icon } from "shortcutsflow";

export default defineShortcut({
  name: "Basic Shortcut",
  icon: icon.create(icon.color.blue, icon.glyph.shortcuts),
  workflow: (shortcut) => {
    const message = shortcut.text("Hello from ShortcutsFlow");
    shortcut.showResult(message);
  },
});
`,
    },
    {
      path: "tsconfig.json",
      contents: `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true,
    "skipLibCheck": true,
    "noEmit": true
  },
  "include": [
    "src/**/*.ts",
    "shortcuts.config.ts"
  ]
}
`,
    },
    {
      path: ".gitignore",
      contents: `node_modules
dist
`,
    },
    {
      path: "README.md",
      contents: `# ${projectName}

ShortcutsFlow project generated by \`create-shortcutsflow\`.

## Commands

\`\`\`bash
npm install
npm run build
npm run check
npm run inspect
npm run sign
\`\`\`

Generated files are written to \`dist/\`.
`,
    },
  ];
}

/**
 * 创建开发者项目的 package.json 内容。
 */
function createPackageJson(projectName: string): Record<string, unknown> {
  return {
    name: projectName,
    version: "0.1.0",
    private: true,
    type: "module",
    scripts: {
      build: "shortcutsflow build",
      check: "shortcutsflow check",
      inspect: `shortcutsflow inspect dist/${shortcutOutputBase}.unsigned.shortcut`,
      sign: `shortcutsflow sign dist/${shortcutOutputBase}.unsigned.shortcut dist/${shortcutOutputBase}.shortcut`,
    },
    dependencies: {
      shortcutsflow: `^${packageVersion}`,
    },
    devDependencies: {
      typescript: "^5.8.0",
    },
  };
}

/**
 * 读取 create-shortcutsflow 自身的发布版本。
 */
function readPackageVersion(): string {
  const packageJson = JSON.parse(
    readFileSync(new URL("../package.json", import.meta.url), "utf8"),
  ) as {
    version?: string;
  };

  if (!packageJson.version) {
    throw new Error("Missing package version.");
  }

  return packageJson.version;
}

/**
 * 将目录名转换为 npm package name。
 */
function normalizePackageName(value: string): string {
  const normalized = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return normalized || "shortcutsflow-project";
}

/**
 * 输出初始化器使用说明。
 */
function printHelp(): void {
  console.log(`Usage:
  npm create shortcutsflow <project-name>
  npx create-shortcutsflow <project-name>`);
}

main(process.argv.slice(2));
